variables:
  buildConfiguration: 'Release'
  outputDir: '$(Build.ArtifactStagingDirectory)/drop'
  androidSdkVersion: '35'
  androidHome: '$(Agent.ToolsDirectory)/android-sdk'
  javaHome: 'C:\Java\OpenJDK11'

trigger:
  branches:
    include:
      - main
      - master
      - feature/*
      - release/*

pool:
  vmImage: 'windows-latest'

stages:
- stage: Versioning
  jobs:
  - job: GitVersion
    steps:
    - checkout: self
      fetchDepth: 0

    - script: |
        dotnet new tool-manifest --force
        dotnet tool install GitVersion.Tool --version 6.3.0
        dotnet tool run dotnet-gitversion /output json /verbosity quiet > gitversion.json
      displayName: 'Install and Run GitVersion'

    - task: PowerShell@2
      displayName: 'Set GitVersion-based Build Number'
      inputs:
        targetType: 'inline'
        script: |
          $gitVersion = Get-Content 'gitversion.json' | ConvertFrom-Json
          if ($gitVersion -and $gitVersion.MajorMinorPatch) {
              $buildVersion = "v$($gitVersion.MajorMinorPatch).$(Build.BuildNumber)"
              Write-Host "##vso[build.updatebuildnumber]$buildVersion"
              Write-Host "##vso[task.setvariable variable=GitVersion_BuildVersion]$buildVersion"
          }

- stage: Build
  dependsOn: Versioning
  jobs:
  - job: Build_Android
    steps:
    - checkout: self

    - task: UseDotNet@2
      displayName: 'Install .NET SDK 9.x'
      inputs:
        version: '9.x'
        includePreviewVersions: true

    - task: PowerShell@2
      displayName: 'Install OpenJDK 11'
      inputs:
        targetType: 'inline'
        script: |
          $jdkUrl = "https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.21+9/OpenJDK11U-jdk_x64_windows_hotspot_11.0.21_9.msi"
          $installerPath = "$env:TEMP\openjdk11.msi"
          Invoke-WebRequest -Uri $jdkUrl -OutFile $installerPath
          Start-Process msiexec.exe -Wait -ArgumentList "/i `"$installerPath`" INSTALLDIR=`"$(javaHome)`" /quiet /qn /norestart"
          Write-Host "##vso[task.setvariable variable=JAVA_HOME]$(javaHome)"

    - task: PowerShell@2
      displayName: 'Download Android SDK CLI Tools'
      inputs:
        targetType: 'inline'
        script: |
          $sdkRoot = "$(androidHome)"
          $toolsUrl = "https://dl.google.com/android/repository/commandlinetools-win-9477386_latest.zip"
          $zipPath = "$sdkRoot\cmdline-tools.zip"
          $extractTemp = "$sdkRoot\temp"
          $finalToolsDir = "$sdkRoot\cmdline-tools\latest"

          New-Item -ItemType Directory -Force -Path $sdkRoot | Out-Null
          Invoke-WebRequest -Uri $toolsUrl -OutFile $zipPath
          Expand-Archive -Path $zipPath -DestinationPath $extractTemp -Force
          New-Item -ItemType Directory -Force -Path $finalToolsDir | Out-Null
          Copy-Item "$extractTemp\cmdline-tools\*" -Destination $finalToolsDir -Recurse -Force
          Remove-Item $extractTemp -Recurse -Force
          Remove-Item $zipPath -Force

          Write-Host "##vso[task.setvariable variable=ANDROID_HOME]$sdkRoot"
          Write-Host "##vso[task.setvariable variable=PATH]$sdkRoot\platform-tools;$sdkRoot\cmdline-tools\latest\bin;$env:PATH"

    - script: |
        "%ANDROID_HOME%\cmdline-tools\latest\bin\sdkmanager.bat" --sdk_root="%ANDROID_HOME%" "platform-tools" "platforms;android-$(androidSdkVersion)" "build-tools;34.0.0" "emulator"
      env:
        ANDROID_HOME: $(ANDROID_HOME)
        JAVA_HOME: $(JAVA_HOME)
        PATH: $(PATH)
      displayName: 'Install Android SDK components'

    - task: DotNetCoreCLI@2
      displayName: 'Restore MAUI Workloads'
      inputs:
        command: 'custom'
        custom: 'workload'
        arguments: 'restore'

    - task: DotNetCoreCLI@2
      displayName: 'Install MAUI Workloads'
      inputs:
        command: 'custom'
        custom: 'workload'
        arguments: install maui maui-android maui-ios maui-windows

    - task: NuGetCommand@2
      displayName: 'Restore NuGet Packages'
      inputs:
        restoreSolution: 'Photography.sln'

    - task: DotNetCoreCLI@2
      displayName: 'Build APK'
      inputs:
        command: 'build'
        projects: '**/Location.Core.csproj'
        arguments: >
          -f net9.0-android
          -p:Configuration=$(buildConfiguration)
          -p:OutputPath=$(outputDir)-apk
          -p:Version=$(GitVersion_BuildVersion)
      env:
        ANDROID_HOME: $(ANDROID_HOME)
        JAVA_HOME: $(JAVA_HOME)
        PATH: $(PATH)

    - task: DotNetCoreCLI@2
      displayName: 'Build AAB'
      inputs:
        command: 'build'
        projects: '**/Location.Core.csproj'
        arguments: >
          -f net9.0-android
          -p:Configuration=$(buildConfiguration)
          -p:OutputPath=$(outputDir)-aab
          -p:AndroidPackageFormat=aab
          -p:Version=$(GitVersion_BuildVersion)
      env:
        ANDROID_HOME: $(ANDROID_HOME)
        JAVA_HOME: $(JAVA_HOME)
        PATH: $(PATH)

- stage: Publish
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: PublishArtifacts
    steps:
    - script: |
        echo "Pushing APK to Azure Artifacts Feed (apks)..."
        az artifacts universal publish --organization https://dev.azure.com/$(organization) --feed $(apksFeed) --package-name location-core-apk --package-version $(GitVersion_BuildVersion) --path $(outputDir)-apk
      displayName: 'Push APK to apks Feed'

    - script: |
        echo "Pushing AAB to Azure Artifacts Feed (aabs)..."
        az artifacts universal publish --organization https://dev.azure.com/$(organization) --feed $(aabsFeed) --package-name location-core-aab --package-version $(GitVersion_BuildVersion) --path $(outputDir)-aab
      displayName: 'Push AAB to aabs Feed'
