trigger:
  branches:
    include:
      - main
      - master
      - feature/*
      - release/*
  tags:
    include:
      - '*'

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  outputDir: '$(Build.ArtifactStagingDirectory)/drop'
  CI: true

stages:
- stage: Build
  jobs:
  - job: Build_MAUI
    pool:
      vmImage: 'windows-latest'

    steps:
    - checkout: self
      fetchDepth: 0
      persistCredentials: true

    - script: |
        git fetch --tags --force --prune
        git tag
      displayName: 'Ensure full Git history and tags are available'

    - task: PowerShell@2
      displayName: 'Install and Run GitVersion'
      inputs:
        targetType: 'inline'
        script: |
          # Install and run GitVersion
          dotnet new tool-manifest --force
          dotnet tool install GitVersion.Tool --version 6.3.0
          $gitVersionOutput = dotnet tool run dotnet-gitversion /output json /verbosity quiet 2>&1
          $gitVersionOutput | Out-File -FilePath gitversion.log -Encoding utf8
          $gitVersionOutput | ConvertFrom-Json | Out-File -FilePath gitversion.json -Encoding utf8

          # Log the output
          Write-Host "GitVersion output file content:"
          Get-Content gitversion.json
          Write-Host "GitVersion log content:"
          Get-Content gitversion.log

    - task: PowerShell@2
      displayName: 'Parse GitVersion and Set Variables'
      inputs:
        targetType: 'inline'
        script: |
          # Parse GitVersion output
          $gitVersion = Get-Content 'gitversion.json' | ConvertFrom-Json
          $semver = $gitVersion.SemVer
          $assemblyVer = $gitVersion.AssemblySemVer
          $fileVer = $gitVersion.AssemblySemFileVer
          $infoVer = $gitVersion.InformationalVersion

          # Set the build number and GitVersion variables
          Write-Host "##vso[build.updatebuildnumber]$semver"
          Write-Host "##vso[task.setvariable variable=GitVersion_SemVer]$semver"
          Write-Host "##vso[task.setvariable variable=GitVersion_AssemblySemVer]$assemblyVer"
          Write-Host "##vso[task.setvariable variable=GitVersion_AssemblySemFileVer]$fileVer"
          Write-Host "##vso[task.setvariable variable=GitVersion_InformationalVersion]$infoVer"

    - script: |
        echo "Using GitVersion: $(GitVersion_SemVer)"
        echo "AssemblyVersion: $(GitVersion_AssemblySemVer)"
        echo "FileVersion: $(GitVersion_AssemblySemFileVer)"
        echo "InformationalVersion: $(GitVersion_InformationalVersion)"
      displayName: 'Confirm GitVersion Output'

    - task: UseDotNet@2
      displayName: 'Install .NET SDK 9.x'
      inputs:
        version: '9.x'
        includePreviewVersions: true

    - script: |
        dotnet workload restore
      displayName: 'Restore Workloads'

    - script: |
        dotnet workload install maui-ios maccatalyst
      displayName: 'Install MAUI iOS Workload'

    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: '**/*.sln'
        feedsToUse: 'select'

    - task: VSBuild@1
      displayName: 'Build MAUI Solution'
      inputs:
        solution: 'Photography.sln'
        configuration: '$(buildConfiguration)'
        msbuildArgs: >
          -p:AssemblyVersion=$(GitVersion_AssemblySemVer)
          -p:FileVersion=$(GitVersion_AssemblySemFileVer)
          -p:InformationalVersion=$(GitVersion_InformationalVersion)

    - task: DotNetCoreCLI@2
      displayName: 'Run Tests'
      inputs:
        command: 'test'
        projects: '**/*Tests.csproj'
        arguments: '--configuration Release --no-build'
      continueOnError: true

    - task: DotNetCoreCLI@2
      displayName: 'Publish MAUI App'
      inputs:
        command: publish
        publishWebProjects: false
        projects: '**/Location.Core.csproj'
        arguments: >
          --framework net9.0-android35.0
          --configuration Release
          --output $(outputDir)
          -p:Version=$(GitVersion_SemVer)
          -p:AssemblyVersion=$(GitVersion_AssemblySemVer)
          -p:FileVersion=$(GitVersion_AssemblySemFileVer)
          -p:InformationalVersion=$(GitVersion_InformationalVersion)

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(outputDir)'
        ArtifactName: 'drop'
