trigger:
  branches:
    include:
      - master
      - main
      - feature/*
      - release/*

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  outputDir: '$(Build.ArtifactStagingDirectory)/drop'
  CI: true
  MY_PAT: $(MY_PAT) # Ensure that MY_PAT is stored securely

stages:
- stage: Build
  jobs:
  - job: Build_MAUI
    pool:
      vmImage: 'windows-latest'
    steps:
    # Checkout the repository with full history to fetch all tags
    - checkout: self
      fetchDepth: 0  # Ensure full history is fetched, including all tags

    # Set up Git credentials using MY_PAT
    - script: |
        git config --global user.name "Your Name"
        git config --global user.email "your-email@example.com"
        echo "https://$(MY_PAT)@dev.azure.com" > .git-credentials
        git config --global credential.helper store
      displayName: 'Set up Git credentials'

    # Install .NET SDK
    - task: UseDotNet@2
      displayName: 'Install .NET SDK 9.x'
      inputs:
        version: '9.x'
        includePreviewVersions: true

    # Install GitVersion tool via dotnet CLI
    - script: |
        echo "Current directory: %CD%"
        dir
        dotnet new tool-manifest --force
        dotnet tool install GitVersion.Tool --version 6.3.0
        dotnet tool list
        dotnet tool run dotnet-gitversion /output json /verbosity quiet > gitversion.json 2> gitversion.log
        echo "GitVersion output file content:"
        type gitversion.json
        echo "GitVersion log content:"
        type gitversion.log
      workingDirectory: $(Build.SourcesDirectory)
      displayName: 'Install and Run GitVersion'

    # PowerShell script to parse GitVersion JSON and set build number
    - task: PowerShell@2
      displayName: 'Parse GitVersion and Set Variables'
      inputs:
        targetType: 'inline'
        script: |
          $gitVersion = Get-Content 'gitversion.json' | ConvertFrom-Json
          Write-Host "Setting build number to $($gitVersion.SemVer)"
          Write-Host "##vso[build.updatebuildnumber]$($gitVersion.SemVer)"
          Write-Host "##vso[task.setvariable variable=GitVersion_SemVer]$($gitVersion.SemVer)"

    # Confirm build number
    - script: |
        echo "Using GitVersion: $(GitVersion_SemVer)"
      displayName: 'Confirm Build Number'

    # Output the tags from the Git repository
    - script: |
        echo "Fetching tags from Git..."
        git fetch --tags
        git tag
      displayName: 'Output Git Tags'

    # Restore workloads
    - script: |
        dotnet workload restore
      displayName: 'Restore Workloads'

    # Install MAUI iOS workload
    - script: |
        dotnet workload install maui-ios maccatalyst
      displayName: 'Install MAUI iOS Workload'

    # Restore NuGet packages
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: '**/*.sln'
        feedsToUse: 'select'

    # Build MAUI solution
    - task: VSBuild@1
      displayName: 'Build MAUI Solution'
      inputs:
        solution: 'Photography.sln'
        configuration: '$(buildConfiguration)'
        msbuildArgs: '-p:ContinuousIntegrationBuild=true -p:Version=$(GitVersion_SemVer)'

    # Run tests
    - task: DotNetCoreCLI@2
      displayName: 'Run Tests'
      inputs:
        command: 'test'
        projects: '**/*Tests.csproj'
        arguments: '--configuration Release --no-build'
      continueOnError: true

    # Publish MAUI app
    - task: DotNetCoreCLI@2
      displayName: 'Publish MAUI App'
      inputs:
        command: publish
        publishWebProjects: false
        projects: '**/Location.Core.csproj'
        arguments: '--framework net9.0-android35.0 --configuration Release --output $(outputDir) -p:Version=$(GitVersion_SemVer)'

    # Publish build artifacts
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(outputDir)'
        ArtifactName: 'drop'
