trigger:
  branches:
    include:
      - main
      - master
      - feature/*
      - release/*

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  outputDir: '$(Build.ArtifactStagingDirectory)/drop'
  androidSdkVersion: '35'
  androidHome: '$(Agent.ToolsDirectory)/android-sdk'
  javaHome: 'C:\Java\OpenJDK11'

stages:
- stage: Build
  jobs:
  - job: Build_MAUI_Android
    steps:
    - checkout: self
      fetchDepth: 0

    - task: UseDotNet@2
      inputs:
        version: '9.x'
        includePreviewVersions: true

    - task: PowerShell@2
      displayName: 'Install OpenJDK 11'
      inputs:
        targetType: 'inline'
        script: |
          $installerUrl = "https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.21+9/OpenJDK11U-jdk_x64_windows_hotspot_11.0.21_9.msi"
          $installerPath = "$env:TEMP\openjdk.msi"
          $installDir = "$(javaHome)"
          Invoke-WebRequest -Uri $installerUrl -OutFile $installerPath
          Start-Process msiexec.exe -Wait -ArgumentList "/i `"$installerPath`" INSTALLDIR=`"$installDir`" /quiet /qn /norestart"
          Write-Host "##vso[task.setvariable variable=JAVA_HOME]$installDir"
          Write-Host "Installed Java to $installDir"

    - task: PowerShell@2
      displayName: 'Install Android Command-Line Tools'
      inputs:
        targetType: 'inline'
        script: |
          $sdkRoot = "$(androidHome)"
          $toolsUrl = "https://dl.google.com/android/repository/commandlinetools-win-9477386_latest.zip"
          $zipPath = "$sdkRoot\cmdline-tools.zip"
          $tempDir = "$sdkRoot\temp"
          $finalDir = "$sdkRoot\cmdline-tools\latest"
          New-Item -ItemType Directory -Force -Path $sdkRoot | Out-Null
          Invoke-WebRequest -Uri $toolsUrl -OutFile $zipPath
          Expand-Archive -Path $zipPath -DestinationPath $tempDir -Force
          Move-Item "$tempDir\cmdline-tools" "$finalDir"
          Remove-Item $tempDir, $zipPath -Recurse -Force
          Write-Host "##vso[task.setvariable variable=ANDROID_HOME]$sdkRoot"

    - script: |
        "%ANDROID_HOME%\cmdline-tools\latest\bin\sdkmanager.bat" --sdk_root=%ANDROID_HOME% `
          "platform-tools" `
          "platforms;android-$(androidSdkVersion)" `
          "build-tools;34.0.0" `
          "emulator"
      displayName: 'Install Android SDK Packages'
      env:
        JAVA_HOME: $(javaHome)
        ANDROID_HOME: $(androidHome)

    - script: |
        echo "Updating PATH..."
        echo "##vso[task.setvariable variable=PATH]$(ANDROID_HOME)\platform-tools;$(ANDROID_HOME)\cmdline-tools\latest\bin;$(PATH)"
      displayName: 'Set Android SDK on PATH'

    - script: |
        dotnet workload install maui maui-android
      displayName: 'Install MAUI Workloads'

    - task: NuGetToolInstaller@1

    - script: |
        dotnet restore
      displayName: 'Restore NuGet Packages'

    - script: |
        dotnet build --configuration $(buildConfiguration)
      displayName: 'Build MAUI Android App'

    - script: |
        dotnet publish **/*.csproj `
          -f net9.0-android$(androidSdkVersion).0 `
          -c $(buildConfiguration) `
          -o $(outputDir) `
          -p:AndroidPackageFormat=aab
      displayName: 'Publish AAB'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(outputDir)'
        ArtifactName: 'android-aab'

    - script: |
        dotnet publish **/*.csproj `
          -f net9.0-android$(androidSdkVersion).0 `
          -c $(buildConfiguration) `
          -o $(outputDir)-apk `
          -p:AndroidPackageFormat=apk
      displayName: 'Publish APK'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(outputDir)-apk'
        ArtifactName: 'android-apk'
