trigger:
  branches:
    include:
      - master
      - main
      - feature/*
      - release/*

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  outputDir: '$(Build.ArtifactStagingDirectory)/drop'
  CI: true

stages:
- stage: Build
  jobs:
  - job: Build_MAUI
    pool:
      vmImage: 'windows-latest'

    steps:
    - checkout: self
      fetchDepth: 0
      persistCredentials: true

    - script: |
        git fetch --tags --force --prune
      displayName: 'Ensure full Git history and tags are available'

    - script: |
        echo "Current directory: %CD%"
        dir
        dotnet new tool-manifest --force
        dotnet tool install GitVersion.Tool --version 6.3.0
        dotnet tool list
        dotnet tool run dotnet-gitversion /output json /verbosity quiet > gitversion.json 2> gitversion.log
        echo "GitVersion output file content:"
        type gitversion.json
        echo "GitVersion log content:"
        type gitversion.log
      workingDirectory: $(Build.SourcesDirectory)
      displayName: 'Install and Run GitVersion'

    - task: PowerShell@2
      displayName: 'Update Build Number from GitVersion with Default Value'
      inputs:
        targetType: 'inline'
        script: |
          $gitVersion = Get-Content 'gitversion.json' | ConvertFrom-Json
          if ($gitVersion -and $gitVersion.SemVer) {
              $semver = $gitVersion.SemVer
          } else {
              $semver = '0.5.0'
              Write-Host "GitVersion output is invalid or missing. Using default version: $semver"
          }
          Write-Host "Setting build number to $semver"
          Write-Host "##vso[build.updatebuildnumber]$semver"
          Write-Host "##vso[task.setvariable variable=GitVersion_SemVer]$semver"

    - script: |
        echo "Using GitVersion: $(GitVersion_SemVer)"
      displayName: 'Confirm Build Number'

    - script: |
        dotnet workload restore
        dotnet workload install maui
      displayName: 'Restore & Install MAUI Workloads'

    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: '**/*.sln'
        feedsToUse: 'select'

    - task: VSBuild@1
      displayName: 'Build MAUI Solution'
      inputs:
        solution: 'Photography.sln'
        configuration: '$(buildConfiguration)'
        msbuildArgs: '-p:ContinuousIntegrationBuild=true -p:Version=$(GitVersion_SemVer)'

    - task: DotNetCoreCLI@2
      displayName: 'Run Tests'
      inputs:
        command: 'test'
        projects: '**/*.Tests.csproj'
        arguments: '--configuration Release --no-build'
      continueOnError: true

    - task: DotNetCoreCLI@2
      displayName: 'Publish MAUI Android App'
      inputs:
        command: publish
        publishWebProjects: false
        projects: '**/Location.Core.csproj' # replace with your actual Android project
        arguments: '--framework net9.0-android35.0 --configuration Release --output $(outputDir) -p:Version=$(GitVersion_SemVer)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(outputDir)'
        ArtifactName: 'drop'
