trigger:
  branches:
    include:
      - main
      - feature/*
      - release/*

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  outputDir: '$(Build.ArtifactStagingDirectory)/drop'
  CI: true

stages:
- stage: Build
  jobs:
  - job: Build_MAUI
    pool:
      vmImage: 'windows-latest'

    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET SDK 9.x'
      inputs:
        version: '9.x'
        includePreviewVersions: true
    - script: |
        dotnet workload restore
      displayName: 'Restore Workloads'
    - script: |
        dotnet workload install maui-ios maccatalyst
      displayName: 'Install MAUI iOS Workload'

    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: '**/*.sln'
        feedsToUse: 'select'

    - script: |
        dotnet workload restore
      displayName: 'Restore .NET Workloads'

    - script: |
        dotnet build Photography.sln --configuration $(buildConfiguration) -p:ContinuousIntegrationBuild=true
      displayName: 'Build MAUI Solution'

    - script: |
        dotnet publish Location.Core/Location.Core.csproj -c $(buildConfiguration) -o $(outputDir) -p:Version=$(Build.BuildNumber)
      displayName: 'Publish MAUI App'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(outputDir)'
        ArtifactName: 'drop'