trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true
  
- script: |
    git remote add github https://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@github.com/brokerandyT2/PhotographyTesting.git
    git push github HEAD:main -f
  displayName: 'Push to GitHub'