trigger:
  branches:
    include:
      - main
      - feature/*
      - release/*

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  solution: 'Photography.sln'
  CI: true
steps:
# Install .NET SDK (ensure it's the version MAUI requires)
- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '9.x' # Use the .NET version your MAUI project uses



# Restore NuGet packages
- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet packages'
  inputs:
    command: 'restore'
    projects: '$(solution)'

- task: VSBuild@1
  displayName: 'Build MAUI Android using MSBuild (Visual Studio)'
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:Configuration=$(buildConfiguration) /p:Platform=AnyCPU'# /p:Version=$(GitVersion.SemVer)'
    platform: 'Any CPU'
    configuration: '$(buildConfiguration)'

# (Optional) Pack or Publish if needed
# - task: DotNetCoreCLI@2
#   displayName: 'Publish'
#   inputs:
#     command: 'publish'
#     publishWebProjects: false
#     projects: '$(solution)'
#     arguments: '--configuration $(buildConfiguration)'
