trigger:
  branches:
    include:
      - main
      - master
      - feature/*
      - release/*

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  outputDir: '$(Build.ArtifactStagingDirectory)/drop'
  androidSdkVersion: '35'
  androidHome: '$(Agent.ToolsDirectory)/android-sdk'

stages:
- stage: Build
  jobs:
  - job: Build_MAUI_Android
    pool:
      vmImage: 'windows-latest'

    steps:
    - checkout: self
      fetchDepth: 0

    # Install .NET SDK
    - task: UseDotNet@2
      displayName: 'Install .NET SDK 9.x'
      inputs:
        version: '9.x'
        includePreviewVersions: true

    # Install OpenJDK 11 and set JAVA_HOME
    - task: PowerShell@2
      displayName: 'Install OpenJDK 11 and Set JAVA_HOME'
      inputs:
        targetType: 'inline'
        script: |
          $jdkVersion = "11"
          $installerUrl = "https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.21+9/OpenJDK11U-jdk_x64_windows_hotspot_11.0.21_9.msi"
          $installerPath = "$env:Temp\openjdk.msi"
          $installDir = "C:\Java\OpenJDK$jdkVersion"

          Invoke-WebRequest -Uri $installerUrl -OutFile $installerPath
          Start-Process msiexec.exe -Wait -ArgumentList "/i `"$installerPath`" INSTALLDIR=`"$installDir`" /quiet /qn /norestart"

          [System.Environment]::SetEnvironmentVariable("JAVA_HOME", $installDir, [System.EnvironmentVariableTarget]::Process)
          $env:JAVA_HOME = $installDir
          $env:Path += ";$installDir\bin"

    # Download and set up Android SDK command-line tools
    - task: PowerShell@2
      displayName: 'Download and Set Up Android SDK Command-Line Tools'
      inputs:
        targetType: 'inline'
        script: |
          $sdkRoot = "$(androidHome)"
          $toolsUrl = "https://dl.google.com/android/repository/commandlinetools-win-9477386_latest.zip"
          $zipPath = "$sdkRoot\cmdline-tools.zip"
          $extractTemp = "$sdkRoot\temp"
          $finalToolsDir = "$sdkRoot\cmdline-tools\latest"

          New-Item -ItemType Directory -Force -Path $sdkRoot | Out-Null
          Invoke-WebRequest -Uri $toolsUrl -OutFile $zipPath
          Expand-Archive -Path $zipPath -DestinationPath $extractTemp -Force
          New-Item -ItemType Directory -Force -Path $finalToolsDir | Out-Null
          Copy-Item "$extractTemp\cmdline-tools\*" -Destination $finalToolsDir -Recurse -Force
          Remove-Item $extractTemp -Recurse -Force
          Remove-Item $zipPath -Force
      env:
        ANDROID_HOME: $(androidHome)

    # Install Android SDK components
    - script: |
        "%ANDROID_HOME%\cmdline-tools\latest\bin\sdkmanager.bat" --sdk_root="%ANDROID_HOME%" "platform-tools" "platforms;android-$(androidSdkVersion)" "build-tools;34.0.0" "emulator"
      env:
        ANDROID_HOME: $(androidHome)
        JAVA_HOME: C:\Java\OpenJDK11
      displayName: 'Install Android SDK components'

    # Set environment variables for SDK and Java
    - script: |
        echo "##vso[task.setvariable variable=ANDROID_HOME]$(androidHome)"
        echo "##vso[task.setvariable variable=JAVA_HOME]C:\Java\OpenJDK11"
        echo "##vso[task.setvariable variable=PATH]$(androidHome)\platform-tools;$(androidHome)\cmdline-tools\latest\bin;$(PATH)"
      displayName: 'Set Env Vars'

    # Install NuGet Tool
    - task: NuGetToolInstaller@1

    # Install .NET MAUI workloads (Android, iOS, Windows) without versioning
    - script: |
        dotnet workload install maui maui-android maui-ios maui-windows
      displayName: 'Install .NET MAUI Workloads (Android, iOS, Windows)'

    # Restore NuGet Packages
    - task: NuGetCommand@2
      inputs:
        restoreSolution: 'Photography.sln'
      displayName: 'Restore NuGet Packages'

    # Install MAUI Workloads again to ensure everything is restored
    - task: DotNetCoreCLI@2
      displayName: 'Install MAUI Workloads'
      inputs:
        command: 'custom'
        custom: 'workload'
        arguments: 'restore'

    # Build Photography.sln with MSBuild (for tests)
    - task: VSBuild@1
      displayName: 'Build Photography.sln with MSBuild (for tests)'
      inputs:
        solution: 'Photography.sln'
        msbuildArchitecture: 'x64'
        platform: 'Any CPU'
        configuration: '$(buildConfiguration)'
        vsVersion: 'latest'
        msbuildArgs: '/restore /p:UseDotNetNativeToolchain=false'

    # Install .NET MAUI Workloads again for Android
    - script: |
        dotnet workload install maui maui-android
      displayName: 'Install .NET MAUI Workloads for Android'

    # Publish Android AAB (App Bundle)
    - script: |
        dotnet publish "Locations.Photography.Mobile/Locations.Photography.Mobile.csproj" -f net9.0-android$(androidSdkVersion).0 -c $(buildConfiguration) -o $(outputDir) -p:AndroidPackageFormat=aab
      displayName: 'Publish Android AAB (App Bundle)'

    # Upload AAB Artifact
    - task: PublishBuildArtifacts@1
      displayName: 'Upload AAB Artifact'
      inputs:
        PathtoPublish: '$(outputDir)'
        ArtifactName: 'android-aab'

    # Publish Android APK
    - script: |
        dotnet publish "Locations.Photography.Mobile/Locations.Photography.Mobile.csproj" -f net9.0-android$(androidSdkVersion).0 -c $(buildConfiguration) -o $(outputDir)-apk -p:AndroidPackageFormat=apk
      displayName: 'Publish Android APK'

    # Upload APK Artifact
    - task: PublishBuildArtifacts@1
      displayName: 'Upload APK Artifact'
      inputs:
        PathtoPublish: '$(outputDir)-apk'
        ArtifactName: 'android-apk'

    # Install and Run GitVersion
    - script: |
        echo "Current directory: %CD%"
        dir
        dotnet new tool-manifest --force
        dotnet tool install GitVersion.Tool --version 6.3.0
        dotnet tool list
        dotnet tool run dotnet-gitversion /output json /verbosity quiet > gitversion.json 2> gitversion.log
        echo "GitVersion output file content:"
        type gitversion.json
        cat gitversion.json
        echo "GitVersion log content:"
        type gitversion.log
      workingDirectory: $(Build.SourcesDirectory)
      displayName: 'Install and Run GitVersion'

    # Update Build Number from GitVersion
    - task: PowerShell@2
      displayName: 'Update Build Number from GitVersion'
      inputs:
        targetType: 'inline'
        script: |
          $gitVersion = Get-Content 'gitversion.json' | ConvertFrom-Json
          if ($gitVersion -and $gitVersion.SemVer) {
              $semver = $gitVersion.SemVer
          } else {
              Write-Host "GitVersion output is invalid or missing."
          }
          Write-Host "Setting build number to $semver"
          Write-Host "##vso[build.updatebuildnumber]$semver"
          Write-Host "##vso[task.setvariable variable=GitVersion_SemVer]$semver"

    # Confirm Build Number
    - script: |
        echo "Using GitVersion: $(GitVersion_SemVer)"
      displayName: 'Confirm Build Number'
