trigger:
  branches:
    include:
      - main
      - feature/*
      - release/*

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  outputDir: '$(Build.ArtifactStagingDirectory)/drop'
  CI: true

stages:
- stage: Build
  jobs:
  - job: Build_MAUI
    pool:
      vmImage: 'windows-latest'

    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET SDK 9.x'
      inputs:
        version: '9.x'
        includePreviewVersions: true

    - script: |
        dotnet new tool-manifest
        dotnet tool install GitVersion.Tool --version 5.x
        dotnet tool run gitversion /output json > gitversion.json
      displayName: 'Install and Run GitVersion'

    - task: PowerShell@2
      displayName: 'Extract SemVer from GitVersion'
      inputs:
        targetType: 'inline'
        script: |
          $gitVersion = Get-Content "gitversion.json" | ConvertFrom-Json
          $semver = $gitVersion.SemVer
          Write-Host "##vso[build.updatebuildnumber]$semver"
          Write-Host "##vso[task.setvariable variable=GitVersion_SemVer]$semver"

    - script: |
        echo "Using GitVersion: $(GitVersion_SemVer)"
      displayName: 'Confirm GitVersion Output'

    - script: |
        dotnet workload restore
      displayName: 'Restore Workloads'

    - script: |
        dotnet workload install maui-ios maccatalyst
      displayName: 'Install MAUI iOS Workload'

    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: '**/*.sln'
        feedsToUse: 'select'

    - task: VSBuild@1
      displayName: 'Build MAUI Solution'
      inputs:
        solution: 'Photography.sln'
        configuration: '$(buildConfiguration)'
        msbuildArgs: '-p:ContinuousIntegrationBuild=true -p:Version=$(GitVersion_SemVer)'

    - task: DotNetCoreCLI@2
      displayName: 'Run Tests'
      inputs:
        command: 'test'
        projects: '**/*Tests.csproj'
        arguments: '--configuration Release --no-build'

    - task: DotNetCoreCLI@2
      displayName: 'Publish MAUI App'
      inputs:
        command: publish
        publishWebProjects: false
        projects: '**/Location.Core.csproj'
        arguments: '--framework net9.0-android35.0 --configuration Release --output $(outputDir) -p:Version=$(GitVersion_SemVer)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(outputDir)'
        ArtifactName: 'drop'
