#https://learn.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?view=azure-devops

trigger:
  branches:
    include:
      - main
      - master
      - feature/*
      - release/*
  paths:
    include:
      - '**'
    exclude:
      - '!GooglePlaySubscriptionChecker/GooglePlaySubscriptionChecker/**'
pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  outputDir: '$(Build.ArtifactStagingDirectory)/drop'

stages:
- stage: Build
  jobs:
    - job: BuildProject
      steps:
        - checkout: self

        - task: UseDotNet@2
          displayName: 'Install .NET 8 SDK'
          inputs:
            version: '8.x'
            includePreviewVersions: false

        - task: DotNetCoreCLI@2
          displayName: 'Restore NuGet Packages'
          inputs:
            command: 'restore'
            projects: 'GooglePlaySubscriptionChecker/GooglePlaySubscriptionChecker.csproj'

        - task: DotNetCoreCLI@2
          displayName: 'Build Project'
          inputs:
            command: 'build'
            projects: 'GooglePlaySubscriptionChecker/GooglePlaySubscriptionChecker.csproj'
            arguments: '--configuration $(buildConfiguration)'

        - task: DotNetCoreCLI@2
          displayName: 'Publish Project'
          inputs:
            command: 'publish'
            publishWebProjects: false
            projects: 'GooglePlaySubscriptionChecker/GooglePlaySubscriptionChecker.csproj'
            arguments: '--configuration $(buildConfiguration) --output $(outputDir)'

        - publish: '$(outputDir)'
          artifact: drop
