trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'windows-latest'

variables:
  - group: PixMapKeystores  # Import the PixMapKeystores variable group
  - name: BuildConfiguration
    value: 'Release'
  - name: AndroidSdkVersion
    value: '34.0'


steps:
  # Step 1: Verify Non-Secret Variables
  - script: |
      echo "Verifying pipeline setup..."
      echo "Feed Name: apk"
      echo "Package Name: LocationCore_APK"
    displayName: 'Verify Non-Secret Variables'

  # Step 2: Install .NET SDK
  - task: UseDotNet@2
    displayName: 'Install .NET SDK'
    inputs:
      packageType: 'sdk'
      version: '9.x'

  # Step 3: Install .NET MAUI Android Workload
  - script: |
      dotnet workload install maui-android
    displayName: 'Install .NET MAUI Android Workload'

  # Step 4: Install Android SDK and Command-Line Tools
  - script: |
      echo "Installing Android SDK..."
      choco install android-sdk -y
      refreshenv

      set ANDROID_SDK_ROOT=C:\Android\android-sdk
      set CMDLINE_TOOLS_DIR=%ANDROID_SDK_ROOT%\cmdline-tools\latest
      mkdir %CMDLINE_TOOLS_DIR%

      curl -o cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-win-11076708_latest.zip
      tar -xf cmdline-tools.zip -C %CMDLINE_TOOLS_DIR% --strip-components=1

      set PATH=%CMDLINE_TOOLS_DIR%\bin;%PATH%
      sdkmanager.bat "platform-tools" "platforms;android-$(AndroidSdkVersion)" "build-tools;$(AndroidSdkVersion)" --sdk_root=%ANDROID_SDK_ROOT%
    displayName: 'Install Android SDK and cmdline-tools'

  # Step 5: Restore NuGet Packages for the Solution
  - task: NuGetCommand@2
    displayName: 'Restore NuGet Packages'
    inputs:
      command: 'restore'
      restoreSolution: '**/Photography.sln'

  # Step 6: Build Unsigned APK
  - task: MSBuild@1
    displayName: 'Build Unsigned APK'
    inputs:
      solution: '**/Location.Core.csproj'
      msbuildArguments: '/p:Configuration=$(BuildConfiguration) /p:AndroidPackageFormat=apk'
      configuration: '$(BuildConfiguration)'
  - script: |
      echo "Listing files in output directory..."
      dir $(Build.SourcesDirectory)\bin\$(BuildConfiguration)\net9.0-android\
    displayName: 'List Files in Build Output Directory'

  # Step 7: Download Keystore File
  - task: DownloadSecureFile@1
    displayName: 'Download Keystore File'
    inputs:
      secureFile: 'pixmap-release.keystore'

  # Step 8: Sign APK
  - script: |
      jarsigner -verbose ^
        -keystore "$(Agent.TempDirectory)\pixmap-release.keystore" ^
        -storepass "$(KeystorePassword)" ^
        -keypass "$(KeyPassword)" ^
        -signedjar "$(Build.ArtifactStagingDirectory)\PixMap-$(Build.BuildId).apk" ^
        "$(Build.SourcesDirectory)\bin\$(BuildConfiguration)\net9.0-android\PixMap.apk" ^
        $(KeyAlias)
    displayName: 'Sign APK'
    env:
      KeystorePassword: $(KeystorePassword)
      KeyPassword: $(KeyPassword)
      KeyAlias: $(KeyAlias)


  # Step 9: Publish Signed APK to Azure Artifacts
  - task: UniversalPackages@0
    displayName: 'Publish Signed APK to Azure Artifacts'
    inputs:
      command: 'publish'
      publishDirectory: '$(Build.ArtifactStagingDirectory)'
      feedsToUse: 'select'
      feedPublish: 'apk'
      packagePublish: 'LocationCore_APK'
      versionPublish: '1.0.0'
