//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Location.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Location.Core.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Access by Watching Ads.
        /// </summary>
        internal static string AccessIsFreeByWatchingAds {
            get {
                return ResourceManager.GetString("AccessIsFreeByWatchingAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Providing your email address will allow us to backup your data to the cloud.  This is needed so that if you change devices, we can restore your data..
        /// </summary>
        internal static string AddEmail {
            get {
                return ResourceManager.GetString("AddEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Location Tutorial.
        /// </summary>
        internal static string AddLocationTutorial {
            get {
                return ResourceManager.GetString("AddLocationTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Photo.
        /// </summary>
        internal static string AddPhoto {
            get {
                return ResourceManager.GetString("AddPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aperture:.
        /// </summary>
        internal static string aperture {
            get {
                return ResourceManager.GetString("aperture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aperture.
        /// </summary>
        internal static string aperturenocolon {
            get {
                return ResourceManager.GetString("aperturenocolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astronomical Dawn.
        /// </summary>
        internal static string AstronomicalDawn {
            get {
                return ResourceManager.GetString("AstronomicalDawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astronomical Dusk.
        /// </summary>
        internal static string AstronomicalDusk {
            get {
                return ResourceManager.GetString("AstronomicalDusk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Exposure:.
        /// </summary>
        internal static string baseexposure {
            get {
                return ResourceManager.GetString("baseexposure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By not entering your email address, your data will not be backed up to the cloud..
        /// </summary>
        internal static string BlankEmail {
            get {
                return ResourceManager.GetString("BlankEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate: .
        /// </summary>
        internal static string calculate {
            get {
                return ResourceManager.GetString("calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Date:.
        /// </summary>
        internal static string choosedate {
            get {
                return ResourceManager.GetString("choosedate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Location:.
        /// </summary>
        internal static string chooseyourlocation {
            get {
                return ResourceManager.GetString("chooseyourlocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Location Details.
        /// </summary>
        internal static string CloseLocationDetails {
            get {
                return ResourceManager.GetString("CloseLocationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrast.
        /// </summary>
        internal static string Contrast {
            get {
                return ResourceManager.GetString("Contrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string datenocolon {
            get {
                return ResourceManager.GetString("datenocolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        internal static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equivalent Exposure: .
        /// </summary>
        internal static string equivalentexposure {
            get {
                return ResourceManager.GetString("equivalentexposure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate Scene.
        /// </summary>
        internal static string EvaluateScene {
            get {
                return ResourceManager.GetString("EvaluateScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposure Calculator Tutorial.
        /// </summary>
        internal static string ExposureCalculatorTutorial {
            get {
                return ResourceManager.GetString("ExposureCalculatorTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposure Increments: .
        /// </summary>
        internal static string exposureincrements {
            get {
                return ResourceManager.GetString("exposureincrements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposure Calculator is a paid feature.  You may upgrade your {0} plan to the paid tier of {1}.  Or you may watch an adverstisement..
        /// </summary>
        internal static string ExposurePaid {
            get {
                return ResourceManager.GetString("ExposurePaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Value:.
        /// </summary>
        internal static string fixvalue {
            get {
                return ResourceManager.GetString("fixvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecast:.
        /// </summary>
        internal static string Forecast {
            get {
                return ResourceManager.GetString("Forecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f: .
        /// </summary>
        internal static string fStop {
            get {
                return ResourceManager.GetString("fStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f Stop.
        /// </summary>
        internal static string fstopnocolon {
            get {
                return ResourceManager.GetString("fstopnocolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1/1.
        /// </summary>
        internal static string full {
            get {
                return ResourceManager.GetString("full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evening Golden Hour Start:.
        /// </summary>
        internal static string goldenhourevening {
            get {
                return ResourceManager.GetString("goldenhourevening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morning Golden Hour End:.
        /// </summary>
        internal static string goldenhourmorning {
            get {
                return ResourceManager.GetString("goldenhourmorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gusts.
        /// </summary>
        internal static string Gusts {
            get {
                return ResourceManager.GetString("Gusts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1/2.
        /// </summary>
        internal static string half {
            get {
                return ResourceManager.GetString("half", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High:.
        /// </summary>
        internal static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO: .
        /// </summary>
        internal static string iso {
            get {
                return ResourceManager.GetString("iso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO.
        /// </summary>
        internal static string isonocolon {
            get {
                return ResourceManager.GetString("isonocolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude:.
        /// </summary>
        internal static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Meter Tutorial.
        /// </summary>
        internal static string LightMeterTutorial {
            get {
                return ResourceManager.GetString("LightMeterTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Locations Tutorial.
        /// </summary>
        internal static string ListLocationsTutorial {
            get {
                return ResourceManager.GetString("ListLocationsTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed. Please try again..
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude:.
        /// </summary>
        internal static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low:.
        /// </summary>
        internal static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northern Hemisphere.
        /// </summary>
        internal static string NorthernHemisphere {
            get {
                return ResourceManager.GetString("NorthernHemisphere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over or Under Expose:.
        /// </summary>
        internal static string overunderexpose {
            get {
                return ResourceManager.GetString("overunderexpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This process will take some time..
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This process will take some time.  Depending on your device, it could take several minutes..
        /// </summary>
        internal static string pleasewaitlong {
            get {
                return ResourceManager.GetString("pleasewaitlong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Providing your email address will allow us to restore your data should you change devices..
        /// </summary>
        internal static string ProvideEmail {
            get {
                return ResourceManager.GetString("ProvideEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results:.
        /// </summary>
        internal static string results {
            get {
                return ResourceManager.GetString("results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scene Evaluation Tutorial.
        /// </summary>
        internal static string SceneEvaluationTutorial {
            get {
                return ResourceManager.GetString("SceneEvaluationTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select a Photo Tip Type: .
        /// </summary>
        internal static string selectonetiptype {
            get {
                return ResourceManager.GetString("selectonetiptype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send To Exposure Calculator.
        /// </summary>
        internal static string SendToExposureCalculator {
            get {
                return ResourceManager.GetString("SendToExposureCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Tutorial.
        /// </summary>
        internal static string SettingsTutorial {
            get {
                return ResourceManager.GetString("SettingsTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutter.
        /// </summary>
        internal static string shutter {
            get {
                return ResourceManager.GetString("shutter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutter Speed: .
        /// </summary>
        internal static string shutterspeed {
            get {
                return ResourceManager.GetString("shutterspeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutter Speed.
        /// </summary>
        internal static string shutterspeednocolon {
            get {
                return ResourceManager.GetString("shutterspeednocolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar Noon:.
        /// </summary>
        internal static string solarnoon {
            get {
                return ResourceManager.GetString("solarnoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Southern Hemisphere.
        /// </summary>
        internal static string SouthernHemisphere {
            get {
                return ResourceManager.GetString("SouthernHemisphere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Monitoring.
        /// </summary>
        internal static string StartMonitoring {
            get {
                return ResourceManager.GetString("StartMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Expiration:.
        /// </summary>
        internal static string SubscriptionExpiration {
            get {
                return ResourceManager.GetString("SubscriptionExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Subscription:.
        /// </summary>
        internal static string SubscriptionType {
            get {
                return ResourceManager.GetString("SubscriptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun Events.
        /// </summary>
        internal static string SunCalculations {
            get {
                return ResourceManager.GetString("SunCalculations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun Calculations Tutorial.
        /// </summary>
        internal static string SunCalculationsTutorial {
            get {
                return ResourceManager.GetString("SunCalculationsTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun Location Tutorial.
        /// </summary>
        internal static string SunLocationTutorial {
            get {
                return ResourceManager.GetString("SunLocationTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun Rise: .
        /// </summary>
        internal static string Sunrise {
            get {
                return ResourceManager.GetString("Sunrise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun Set:.
        /// </summary>
        internal static string Sunset {
            get {
                return ResourceManager.GetString("Sunset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch.
        /// </summary>
        internal static string Switch {
            get {
                return ResourceManager.GetString("Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Clock Format.
        /// </summary>
        internal static string SwitchClockType {
            get {
                return ResourceManager.GetString("SwitchClockType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swich Date Format.
        /// </summary>
        internal static string SwitchDateFormat {
            get {
                return ResourceManager.GetString("SwitchDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Hemisphere.
        /// </summary>
        internal static string SwitchHemisphere {
            get {
                return ResourceManager.GetString("SwitchHemisphere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Reading.
        /// </summary>
        internal static string TakeReading {
            get {
                return ResourceManager.GetString("TakeReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Scale.
        /// </summary>
        internal static string TemperatureFormat {
            get {
                return ResourceManager.GetString("TemperatureFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to testt.
        /// </summary>
        internal static string Testt {
            get {
                return ResourceManager.GetString("Testt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1/3.
        /// </summary>
        internal static string thirds {
            get {
                return ResourceManager.GetString("thirds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips Tutorial.
        /// </summary>
        internal static string TipsTutorial {
            get {
                return ResourceManager.GetString("TipsTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips Viewed.
        /// </summary>
        internal static string TipViewed {
            get {
                return ResourceManager.GetString("TipViewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Towards Wind.
        /// </summary>
        internal static string TowardsWind {
            get {
                return ResourceManager.GetString("TowardsWind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 Hour Clocks.
        /// </summary>
        internal static string TwelveHourClocks {
            get {
                return ResourceManager.GetString("TwelveHourClocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24 Hour Clocks.
        /// </summary>
        internal static string TwentyFourHourClocks {
            get {
                return ResourceManager.GetString("TwentyFourHourClocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Graphs.
        /// </summary>
        internal static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        internal static string Weather {
            get {
                return ResourceManager.GetString("Weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather Display Tutorial.
        /// </summary>
        internal static string WeatherDisplayTutorial {
            get {
                return ResourceManager.GetString("WeatherDisplayTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to PixMap.  Please take this opportunity to configure your application.  You may return to this screen using the &apos;gear&apos; icon in the top right corner of your screen..
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind Direction.
        /// </summary>
        internal static string Wind {
            get {
                return ResourceManager.GetString("Wind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind Direction.
        /// </summary>
        internal static string WindDirection {
            get {
                return ResourceManager.GetString("WindDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind Speed.
        /// </summary>
        internal static string WindSpeed {
            get {
                return ResourceManager.GetString("WindSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Wind.
        /// </summary>
        internal static string WithWind {
            get {
                return ResourceManager.GetString("WithWind", resourceCulture);
            }
        }
    }
}
