# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Install Workloads
      run: dotnet workload restore
    - name: Install iOS SDK workload
      run: dotnet workload install Microsoft.iOS.Sdk.net9.0_18.4
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
